project_id = "blcfzmugnbojyckzjcew"

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = true

[functions.init-stripe-products]
verify_jwt = false

[functions.purchase-streak-freeze]
verify_jwt = true
